name: Backlog Health Report

on:
  workflow_dispatch:
  push:
    paths:
      - 'agilereporting/latest_snapshot.csv'
      - '.github/scripts/analyze_hierarchy.py'
      - '.github/workflows/backloghealth.yml'

jobs:
  backlog-health:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run Hierarchy Violation Analysis
        run: python .github/scripts/analyze_hierarchy.py

      - name: Upload Backlog Health Reports
        uses: actions/upload-artifact@v3
        with:
          name: backloghealth
          path: |
            backloghealth/hierarchy_violations.csv
            backloghealth/hierarchy_violations.md

      - name: Display markdown report in workflow summary
        if: always()
        run: |
          echo '### Backlog Health Hierarchy Violations' >> $GITHUB_STEP_SUMMARY
          cat backloghealth/hierarchy_violations.md >> $GITHUB_STEP_SUMMARY
