name: Backlog Health Report

on:
  workflow_dispatch:
  push:
    paths:
      - 'agilereporting/latest_snapshot.csv'
      - '.github/scripts/analyze_hierarchy.py'
      - '.github/workflows/backloghealth.yml'

permissions:
  contents: write

jobs:
  backlog-health:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run Hierarchy Violation Analysis
        run: python .github/scripts/analyze_hierarchy.py

      - name: Upload Backlog Health Reports
        uses: actions/upload-artifact@v4
        with:
          name: backloghealth
          path: |
            backloghealth/hierarchy_violations.csv
            backloghealth/hierarchy_violations.md

      - name: Display markdown report in workflow summary
        if: always()
        run: |
          echo '### Backlog Health Hierarchy Violations' >> $GITHUB_STEP_SUMMARY
          cat backloghealth/hierarchy_violations.md >> $GITHUB_STEP_SUMMARY

      - name: Commit and push backlog health reports to repo
        env:
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GH_TOKEN: ${{ secrets.MILESTONE_SYNC }}
        run: |
          git config user.name "${GIT_AUTHOR_NAME}"
          git config user.email "${GIT_AUTHOR_EMAIL}"
          git add backloghealth/hierarchy_violations.md backloghealth/hierarchy_violations.csv # Ensures both files are added
          if git diff --cached --quiet; then
            echo "No changes to backloghealth reports to commit." # Updated message
            exit 0
          fi
          git commit -m "Update backloghealth hierarchy violation reports (csv & md) [automated]" # Updated commit message
          git push https://x-access-token:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD:main
