name: Consolidate burndown facts

on:
  schedule:
    - cron: '0 11 * * *'
  workflow_dispatch:

jobs:
  consolidate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install pandas
        run: pip install pandas

      - name: Run consolidation script with custom token
        env:
          CUSTOM_GITHUB_TOKEN: ${{ secrets.MILESTONE_SYNC }} # <-- your custom PAT secret
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REF: ${{ github.ref }}
        run: python .github/scripts/consolidate_github_snapshots.py
