name: Daily Agile Snapshot

on:
  workflow_dispatch:
  schedule:
    - cron: '5 22 * * *'

permissions:
  contents: write

jobs:
  fetch-backlog-snapshot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python Dependencies
        run: pip install requests

      - name: Run Project Issue Fetch Script
        run: python .github/scripts/fetch_project_issues.py
        env:
          MILESTONE_SYNC_TOKEN: ${{ secrets.MILESTONE_SYNC }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}

      - name: Commit and push Agile Snapshot CSV to repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add agilreporting/project.issues_*.csv agilreporting/latest_snapshot.csv
          if git diff --staged --quiet; then
            echo "Agile snapshot is up-to-date. Nothing to commit."
          else
            git commit -m "Update Agile snapshot (automated)"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
