name: Daily Agile Snapshot CSV (v3 - Python) # Updated name for clarity

on:
  workflow_dispatch: # Manual trigger
  schedule:
    # 5:00 PM Central = 22:00 UTC (adjust as needed)
    - cron: '0 22 * * *'

permissions:
  contents: write # Needed to commit the CSV

jobs:
  fetch-issues:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Or your preferred Python version

      # Step 3: Install required Python packages
      - name: Install Python Dependencies
        run: pip install requests # requests library is needed by the script

      # Step 4: Execute the Python script
      # The script handles fetching, processing, and saving the CSVs
      # It also determines the filenames and outputs them for the commit step
      - name: Run Agile Data Processing Script
        id: python_script # Add an ID to reference outputs
        run: python .github/scripts/fetch_project_issues.py
        env:
          # Pass secrets and config needed by the script as environment variables
          MILESTONE_SYNC_TOKEN: ${{ secrets.MILESTONE_SYNC }}
          PROJECT_ID: "PVT_kwDODH0FwM4A3yi4" # Or use a secret: ${{ secrets.PROJECT_ID }}

      # Step 5: Commit the generated snapshot CSVs to the repository
      - name: Commit and push snapshots to repo
        # Only run if the python script step succeeded AND produced the filename outputs
        if: success() && steps.python_script.outputs.snapshot_filename && steps.python_script.outputs.latest_snapshot_filename
        run: |
          # Get the full paths output by the script
          DATED_SNAPSHOT_PATH="${{ steps.python_script.outputs.snapshot_filename }}"
          LATEST_SNAPSHOT_PATH="${{ steps.python_script.outputs.latest_snapshot_filename }}"

          # Extract just the date part from the dated filename for the commit message
          FILENAME_ONLY=$(basename "$DATED_SNAPSHOT_PATH")
          SNAPSHOT_DATE=${FILENAME_ONLY#project.issues_} # Remove prefix
          SNAPSHOT_DATE=${SNAPSHOT_DATE%.csv} # Remove suffix

          echo "Committing dated snapshot: $DATED_SNAPSHOT_PATH"
          echo "Committing latest snapshot: $LATEST_SNAPSHOT_PATH"

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Add both files generated by the script
          git add "$DATED_SNAPSHOT_PATH"
          git add "$LATEST_SNAPSHOT_PATH"

          # Check if there are changes to commit for these specific files
          # Use the paths for checking the diff
          if git diff --staged --quiet -- "$DATED_SNAPSHOT_PATH" "$LATEST_SNAPSHOT_PATH"; then
            echo "No changes detected in snapshots. Nothing to commit."
          else
            git commit -m "Agile snapshot for $SNAPSHOT_DATE and latest_snapshot (automated)"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Use default token for commit
