name: Daily Milestone Metadata

on:
  schedule:
    - cron: '0 3 * * *' # Runs every day at 03:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  milestone-metadata:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: pip install requests

      - name: Run milestone metadata script
        run: python .github/scripts/fetch_milestones.py
        env:
          MILESTONE_SYNC_TOKEN: ${{ secrets.MILESTONE_SYNC }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}

      - name: Commit and push milestone_metadata.csv if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add agilereportingmetadata/milestone_metadata.csv 2>/dev/null || true
          if git diff --staged --quiet; then
            echo "milestone_metadata.csv is up-to-date. Nothing to commit."
          else
            git commit -m "Update milestone_metadata.csv (automated daily run)"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
