name: Daily Agile Snapshot v3

on:
  workflow_dispatch:
  schedule:
    # 5:00 PM Central = 22:00 UTC
    - cron: '0 22 * * *'

permissions:
  contents: write
  id-token: write

jobs:
  fetch-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Set snapshot filename (Central Time, YYYY.MM.DD)
        id: setvars
        run: |
          SNAPSHOT_DATE=$(TZ='America/Chicago' date +'%Y.%m.%d')
          echo "SNAPSHOT_DATE=$SNAPSHOT_DATE" >> $GITHUB_ENV
          echo "SNAPSHOT_FILENAME=project.issues_${SNAPSHOT_DATE}.csv" >> $GITHUB_ENV

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Export ProjectV2 Issues and Metadata to CSV
        run: |
          mkdir -p agilereporting agilereportingmetadata
          python3 .github/scripts/export_projectv2_issues.py \
            --project-id "PVT_kwDODH0FwM4A3yi4" \
            --token "${{ secrets.MILESTONE_SYNC }}" \
            --out-csv "agilereporting/${SNAPSHOT_FILENAME}" \
            --out-meta "agilereportingmetadata/ProjectFields.csv"

      - name: Commit and push snapshot and metadata to repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add "agilereporting/${SNAPSHOT_FILENAME}"
          git add "agilereportingmetadata/ProjectFields.csv"
          git commit -m "Agile snapshot and project field metadata for $SNAPSHOT_DATE" || echo "Nothing to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
