name: Generate Monthly Status Report

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'  # runs at 00:00 UTC on the 1st of every month

jobs:
  export-closed-issues:
    uses: ./.github/workflows/export_closed_issues.yml

  generate-status-report:
    needs: export-closed-issues
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install OpenAI SDK
        run: pip install openai
      - name: Generate Status Report
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python .github/scripts/generate_status_report.py
      - name: Commit Status Report
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add monthly_report/status_report.md
          git commit -m "Add monthly status report"
          git push
