name: Inherit Parent Issue Fields

on:
  issues:
    types: [opened]

permissions:
  issues: write
  contents: read

jobs:
  inherit-fields:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python Dependencies
        run: pip install requests

      - name: Run Field Inheritance Script
        env:
          # Use a custom PAT if needed, otherwise use GITHUB_TOKEN
          GITHUB_TOKEN: ${{ secrets.milestone_sync }}
          # Pass data about the newly opened issue
          NEW_ISSUE_NODE_ID: ${{ github.event.issue.node_id }}
          NEW_ISSUE_NUMBER: ${{ github.event.issue.number }}
          # Pass repository context
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          # Use repository variable for the ProjectV2 Node ID (recommended, no hardcoded fallback)
          PROJECT_ID: ${{ vars.PROJECT_V2_NODE_ID }}
        run: python .github/scripts/inherit_fields.py
