name: Inherit Fields on Sub-Issue Creation

on:
  issues:
    types: [opened]

jobs:
  inherit-fields:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: pip install requests

      # Create issue step here if you use one, e.g.:
      # - id: create_issue
      #   name: Create issue
      #   run: echo "Simulated" # Replace with your actual issue creation

      - name: Run inherit fields script
        run: python .github/scripts/inherit_fields.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEW_ISSUE_NODE_ID: ${{ steps.create_issue.outputs.node_id }}
          NEW_ISSUE_NUMBER: ${{ steps.create_issue.outputs.issue_number }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
