name: Inherit Parent Fields on Sub-Issue Creation

on:
  issues:
    types: [opened]

jobs:
  inherit-fields:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: pip install requests

      - name: Run inherit fields script
        run: python .github/scripts/inherit_fields.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEW_ISSUE_NODE_ID: ${{ github.event.issue.node_id }}
          NEW_ISSUE_NUMBER: ${{ github.event.issue.number }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
