name: Sync Milestone to Sub-issues

on:
  issues:
    types:
      - milestoned
      - unmilestoned # Also trigger when milestone is removed

permissions:
  # These permissions might still be useful if the PAT doesn't cover everything,
  # but the PAT's permissions will likely take precedence for the script's actions.
  issues: write
  projects: write
  contents: read

jobs:
  sync_milestone:
    runs-on: ubuntu-latest
    if: github.event.action == 'milestoned' || github.event.action == 'unmilestoned'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python Dependencies
        run: pip install requests

      - name: Run Milestone Sync Script
        env:
          # *** CHANGE THIS LINE ***
          # Use the PAT stored in the secret instead of the default token
          GITHUB_TOKEN: ${{ secrets.milestone_sync }}
          # Get data from the event payload
          PARENT_ISSUE_NODE_ID: ${{ github.event.issue.node_id }}
          # Pass milestone number, will be empty string if unmilestoned
          PARENT_MILESTONE_NUMBER: ${{ github.event.issue.milestone.number }}
          PROJECT_ID: "PVT_kwDODH0FwM4A3yi4" # Your specific ProjectV2 Node ID
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
        run: python .github/scripts/sync_milestone.py
