name: milestone_sync

on:
  issues:
    types:
      - milestoned

jobs:
  sync-milestone-to-subissues:
    runs-on: ubuntu-latest
    steps:
      - name: Check parent issue type using GraphQL
        id: check_type
        env:
          GH_TOKEN: ${{ secrets.milestone_sync }}
        run: |
          # Extract repository and issue details
          org="${GITHUB_REPOSITORY%/*}"
          repo="${GITHUB_REPOSITORY#*/}"
          number="${{ github.event.issue.number }}"

          # Validate the issue number
          if [[ -z "$number" || ! "$number" =~ ^[0-9]+$ ]]; then
            echo "ERROR: Invalid issue number: $number"
            exit 1
          fi

          # Debugging output
          echo "DEBUG: Repository Org: $org"
          echo "DEBUG: Repository Name: $repo"
          echo "DEBUG: Issue Number: $number"

          # Query the issue's type using the GraphQL API with the issue_types preview header
          result=$(gh api graphql -H "GraphQL-Features: issue_types" -f owner="$org" -f repo="$repo" -F number=$((number)) -f query='
          query ($owner: String!, $repo: String!, $number: Int!) {
            repository(owner: $owner, name: $repo) {
              issue(number: $number) {
                issueType { name }
              }
            }
          }')
          echo "DEBUG: Raw GraphQL result:"
          echo "$result"

          # Extract issue type from result
          type=$(echo "$result" | jq -r '.data.repository.issue.issueType.name')
          echo "DEBUG: Extracted issue type: $type"
          echo "type=$type" >> $GITHUB_OUTPUT

          # Validate the extracted issue type
          if [ -z "$type" ] || [ "$type" = "null" ]; then
            echo "ERROR: Failed to determine issue type. Exiting."
            exit 1
          fi

      - name: Debug output - show extracted type
        run: |
          echo "CHECK_TYPE_OUTPUT_TYPE=${{ steps.check_type.outputs.type }}"

      # This step will fail (exit 1) if not Bug or Story, stopping the job
      - name: Stop workflow if issue type is not Bug or Story
        if: ${{ steps.check_type.outputs.type != 'Bug' && steps.check_type.outputs.type != 'Story' }}
        run: |
          echo "Issue type is neither 'Bug' nor 'Story'. Stopping workflow."
          exit 1

      - name: Get sub-issues via GraphQL
        id: subissues
        env:
          GH_TOKEN: ${{ secrets.milestone_sync }}
          ISSUE_NODE_ID: ${{ github.event.issue.node_id }}
        run: |
          # Get all sub-issues using the subIssues connection
          gh api graphql -H "GraphQL-Features:sub_issues" -H "GraphQL-Features:issue_types" -F id="$ISSUE_NODE_ID" -f query='
            query($id: ID!) {
              node(id: $id) {
                ... on Issue {
                  subIssues(first: 100) {
                    nodes {
                      number
                      id
                    }
                  }
                }
              }
            }
          ' > result.json
          jq '[.data.node.subIssues.nodes[].number]' result.json > subissues_numbers.json
          jq '[.data.node.subIssues.nodes[].id]' result.json > subissues_ids.json
          echo "numbers=$(cat subissues_numbers.json | jq -c '.')" >> $GITHUB_OUTPUT
          echo "ids=$(cat subissues_ids.json | jq -c '.')" >> $GITHUB_OUTPUT

      - name: Update sub-issues with parent's milestone
        env:
          GH_TOKEN: ${{ secrets.milestone_sync }}
          ISSUE_MILESTONE: ${{ github.event.issue.milestone.number }}
        run: |
          numbers=${{ steps.subissues.outputs.numbers }}
          if [ "$numbers" = "" ] || [ "$numbers" = "[]" ]; then
            echo "No sub-issues found. Exiting."
            exit 0
          fi

          for num in $(echo "$numbers" | jq '.[]'); do
            echo "Updating sub-issue $num with milestone $ISSUE_MILESTONE"
            gh api repos/${{ github.repository }}/issues/$num \
              -X PATCH \
              -F milestone="$ISSUE_MILESTONE"
          done

      - name: Add sub-issues to Project PVT_kwDODH0FwM4A3yi4 (if not already present)
        env:
          GH_TOKEN: ${{ secrets.milestone_sync }}
        run: |
          ids=${{ steps.subissues.outputs.ids }}
          PROJECT_NODE_ID="PVT_kwDODH0FwM4A3yi4"

          if [ "$ids" = "" ] || [ "$ids" = "[]" ]; then
            echo "No sub-issue ids found. Exiting."
            exit 0
          fi

          for issue_id in $(echo "$ids" | jq -r '.[]'); do
            echo "Adding sub-issue node $issue_id to project $PROJECT_NODE_ID"
            gh api graphql -f query='
              mutation($projectId: ID!, $contentId: ID!) {
                addProjectV2ItemById(input: {projectId: $projectId, contentId: $contentId}) {
                  item {
                    id
                  }
                }
              }' -F projectId="$PROJECT_NODE_ID" -F contentId="$issue_id"
          done
