name: milestone_sync

on:
  issues:
    types:
      - milestoned

jobs:
  sync-milestone-to-subissues:
    runs-on: ubuntu-latest
    steps:
      - name: Check parent issue type using GraphQL
        id: check_type
        env:
          GH_TOKEN: ${{ secrets.milestone_sync }}
        run: |
          org="${GITHUB_REPOSITORY%/*}"
          repo="${GITHUB_REPOSITORY#*/}"
          number="${{ github.event.issue.number }}"

          result=$(gh api graphql -H "GraphQL-Features: issue_types" -f owner="$org" -f repository="$repo" -F number="$number" -f query='
          query ($owner: String!, $repository: String!, $number: Int!) {
            repository(owner: $owner, name: $repository) {
              issue(number: $number) {
                issueType { name }
              }
            }
          }')
          type=$(echo "$result" | jq -r '.data.repository.issue.issueType.name')
          echo "type=$type"
          echo "type=$type" >> $GITHUB_OUTPUT

      - name: Exit if issue type is not bug or story
        if: ${{ steps.check_type.outputs.type != 'bug' && steps.check_type.outputs.type != 'story' }}
        run: |
          echo "Issue type is neither 'bug' nor 'story'. Exiting."
          exit 0

      - name: Get sub-issues via GraphQL
        id: subissues
        env:
          GH_TOKEN: ${{ secrets.milestone_sync }}
          ISSUE_NODE_ID: ${{ github.event.issue.node_id }}
        run: |
          gh api graphql -H "GraphQL-Features:sub_issues" -H "GraphQL-Features:issue_types" -F id="$ISSUE_NODE_ID" -f query='
            query($id: ID!) {
              node(id: $id) {
                ... on Issue {
                  subIssues(first: 100) {
                    nodes {
                      number
                      id
                    }
                  }
                }
              }
            }
          ' > result.json
          jq '[.data.node.subIssues.nodes[].number]' result.json > subissues_numbers.json
          jq '[.data.node.subIssues.nodes[].id]' result.json > subissues_ids.json
          echo "numbers=$(cat subissues_numbers.json | jq -c '.')" >> $GITHUB_OUTPUT
          echo "ids=$(cat subissues_ids.json | jq -c '.')" >> $GITHUB_OUTPUT

      - name: Update sub-issues with parent's milestone
        env:
          GH_TOKEN: ${{ secrets.milestone_sync }}
          ISSUE_MILESTONE: ${{ github.event.issue.milestone.number }}
        run: |
          numbers=${{ steps.subissues.outputs.numbers }}
          if [ "$numbers" = "" ] || [ "$numbers" = "[]" ]; then
            echo "No sub-issues found. Exiting."
            exit 0
          fi

          for num in $(echo "$numbers" | jq '.[]'); do
            echo "Updating sub-issue $num with milestone $ISSUE_MILESTONE"
            gh api repos/${{ github.repository }}/issues/$num \
              -X PATCH \
              -F milestone="$ISSUE_MILESTONE"
          done

      - name: Add sub-issues to Project PVT_kwDODH0FwM4A3yi4 (if not already present)
        env:
          GH_TOKEN: ${{ secrets.milestone_sync }}
        run: |
          ids=${{ steps.subissues.outputs.ids }}
          PROJECT_NODE_ID="PVT_kwDODH0FwM4A3yi4"

          if [ "$ids" = "" ] || [ "$ids" = "[]" ]; then
            echo "No sub-issue ids found. Exiting."
            exit 0
          fi

          for issue_id in $(echo "$ids" | jq -r '.[]'); do
            echo "Adding sub-issue node $issue_id to project $PROJECT_NODE_ID"
            gh api graphql -f query='
              mutation($projectId: ID!, $contentId: ID!) {
                addProjectV2ItemById(input: {projectId: $projectId, contentId: $contentId}) {
                  item {
                    id
                  }
                }
              }' -F projectId="$PROJECT_NODE_ID" -F contentId="$issue_id"
          done
