name: Sync Milestone to Sub-issues

on:
  issues:
    types:
      - milestoned
      # Use the correct event type for removal
      - demilestoned
      # Keep 'edited' as a fallback, though demilestoned should be primary
      - edited

permissions:
  issues: write
  contents: read

jobs:
  sync_milestone:
    runs-on: ubuntu-latest
    # --- MODIFIED JOB CONDITION ---
    # Run if:
    # 1. The action is specifically 'milestoned' OR
    # 2. The action is specifically 'demilestoned' OR  <-- Added this check
    # 3. The action is 'edited' AND the 'milestone' field was part of the change
    if: |
      github.event.action == 'milestoned' ||
      github.event.action == 'demilestoned' ||
      (github.event.action == 'edited' && github.event.changes.milestone)
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python Dependencies
        run: pip install requests

      - name: Run Milestone Sync Script
        env:
          # Use the PAT stored in the secret
          GITHUB_TOKEN: ${{ secrets.milestone_sync }}
          # Get data from the event payload
          PARENT_ISSUE_NODE_ID: ${{ github.event.issue.node_id }}
          # This correctly passes the number if milestoned, or empty string if demilestoned/edited-to-remove
          PARENT_MILESTONE_NUMBER: ${{ github.event.issue.milestone.number }}
          PROJECT_ID: "PVT_kwDODH0FwM4A3yi4" # Your specific ProjectV2 Node ID
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
        run: python .github/scripts/sync_milestone.py
