name: Monthly Status Report

on:
  workflow_dispatch:

jobs:
  monthly-status-report:
    name: Monthly Closed Issues Status Report
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: pip install requests

      - name: Run monthly closed issues report
        run: |
          python .github/scripts/monthly_closed_issues_report.py
        env:
          MILESTONE_SYNC: ${{ secrets.MILESTONE_SYNC }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}

      - name: Commit & push monthly closed issues report
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add monthly_report/*_monthlyreport.JSON monthly_report/latest_snapshot.JSON
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: update monthly closed issues report [skip ci]"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
