name: monthly_reporting

on:
  workflow_dispatch:
    inputs:
      team:
        description: 'Team value (must match the project field value exactly)'
        required: true
        type: string

permissions:
  contents: write
  actions: read

jobs:
  export-issues:
    name: Export Closed Issues With Team
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Set up date and team for filenames
        id: vars
        run: |
          FILE_SUFFIX=$(date -u +'%Y.%m.%d')
          TEAM_INPUT="${{ github.event.inputs.team }}"
          TEAM_SAFE=$(echo "$TEAM_INPUT" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9]+/_/g' | sed -E 's/^_+|_+$//g')
          echo "file_suffix=$FILE_SUFFIX" >> "$GITHUB_OUTPUT"
          echo "team_safe=$TEAM_SAFE" >> "$GITHUB_OUTPUT"

      - name: Get owner and repo
        id: repo
        run: |
          owner="${GITHUB_REPOSITORY%%/*}"
          repo="${GITHUB_REPOSITORY##*/}"
          echo "owner=$owner" >> "$GITHUB_OUTPUT"
          echo "repo=$repo" >> "$GITHUB_OUTPUT"

      - name: Run export script
        env:
          GH_TOKEN: ${{ secrets.milestone_sync }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          TEAM_VALUE: ${{ inputs.team }}
          SINCE: $(date -u -d '30 days ago' +'%Y-%m-%dT%H:%M:%SZ')
          OWNER: ${{ steps.repo.outputs.owner }}
          REPO: ${{ steps.repo.outputs.repo }}
          FILE_SUFFIX: ${{ steps.vars.outputs.file_suffix }}
          TEAM_SAFE: ${{ steps.vars.outputs.team_safe }}
        run: |
          python .github/scripts/export_closed_issues_with_team.py

      - name: Commit and push monthly report
        env:
          FILE_SUFFIX: ${{ steps.vars.outputs.file_suffix }}
          TEAM_SAFE: ${{ steps.vars.outputs.team_safe }}
        run: |
          mkdir -p monthly_report
          REPORT_FILE="${TEAM_SAFE}_monthlyreport_${FILE_SUFFIX}.json"
          cp closed_issues_with_team.json monthly_report/${REPORT_FILE}
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add monthly_report/${REPORT_FILE}
          if git diff --staged --quiet; then
            echo "Monthly report is up-to-date. Nothing to commit."
          else
            git commit -m "Add monthly report for ${TEAM_SAFE} on ${FILE_SUFFIX}"
            git push
          fi
