name: Sprint MetaData

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  process-sprints:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python Dependencies
        run: pip install requests

      - name: Run Sprint Metadata Script
        run: python .github/scripts/process_sprints.py
        env:
          MILESTONE_SYNC_TOKEN: ${{ secrets.MILESTONE_SYNC }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}

      - name: Commit and push SprintMetaData.csv
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add agilereportingmetadata/SprintMetaData.csv
          if git diff --staged --quiet; then
            echo "SprintMetaData.csv is up-to-date. Nothing to commit."
          else
            git commit -m "Update SprintMetaData.csv (automated)"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
