name: Daily Sprint Metadata CSV

on:
  workflow_dispatch:
  schedule:
    # 5:05 PM Central = 22:05 UTC (run after the main snapshot)
    - cron: '5 22 * * *'

permissions:
  contents: write
  id-token: write

jobs:
  fetch-sprint-metadata:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fetch Sprint Metadata (ProjectV2 Iteration Field)
        run: |
          set -ex
          # Set your ProjectV2 ID here
          PROJECT_ID="PVT_kwDODH0FwM4A3yi4"
          QUERY=$(cat <<EOF
          query {
            node(id: "$PROJECT_ID") {
              ... on ProjectV2 {
                fields(first: 50) {
                  nodes {
                    ... on ProjectV2IterationField {
                      name
                      configuration {
                        iterations {
                          id
                          title
                          startDate
                          endDate
                          duration
                        }
                      }
                    }
                  }
                }
              }
            }
          }
          EOF
          )
          PAYLOAD=$(jq -n --arg query "$QUERY" '{query: $query}')
          RESPONSE=$(curl -s -H "Authorization: Bearer ${{ secrets.MILESTONE_SYNC }}" \
            -H "Content-Type: application/json" \
            -d "$PAYLOAD" \
            https://api.github.com/graphql)
          echo "$RESPONSE" | jq '.' > sprint-metadata-raw.json
          # Extract Sprint/Iteration metadata
          jq '
            .data.node.fields.nodes[]
            | select(.name == "Sprint" and .configuration.iterations)
            | .configuration.iterations[]
            | [.id, .title, .startDate, .endDate, .duration]
            | @csv
          ' sprint-metadata-raw.json > SprintMetaData.csv

      - name: Move SprintMetaData.csv to agilereportingmetadata directory
        run: |
          mkdir -p agilereportingmetadata
          mv SprintMetaData.csv agilereportingmetadata/SprintMetaData.csv

      - name: Commit and push SprintMetaData.csv to repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add agilereportingmetadata/SprintMetaData.csv
          git commit -m "Sprint metadata snapshot" || echo "Nothing to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
