name: Sync Backlog Sprints

on:
  workflow_dispatch:
    inputs:
      target_team:
        description: "Enter the 'Team' name to target for sub-issue sprint sync. Type 'ALL' to sync for all teams (default)."
        required: true
        default: 'ALL'

permissions:
  contents: read
  issues: write

jobs:
  sync-backlog-sprints:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: pip install requests

      - name: Sync backlog sprints to sub-issues
        run: python .github/scripts/sync_backlog_sprints.py
        env:
          MILESTONE_SYNC_TOKEN: ${{ secrets.MILESTONE_SYNC }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          TARGET_TEAM: ${{ github.event.inputs.target_team }}
          RUN_INITIATOR: ${{ github.actor }}
