name: Sync Backlog Sprints to Sub-issues

on:
  workflow_dispatch: # Manual trigger only

permissions:
  issues: write # Needed by script to potentially add items to projects via addProjectV2ItemById
  contents: read # To checkout code
  # projects: write # Might be needed depending on token scope, add if mutations fail due to permissions

jobs:
  sync_backlog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python Dependencies
        run: pip install requests

      - name: Run Sprint Sync Script
        env:
          # Secrets and Configuration
          MILESTONE_SYNC_TOKEN: ${{ secrets.MILESTONE_SYNC }} # Ensure this token has repo, project, issue read/write scope
          PROJECT_ID: "PVT_kwDODH0FwM4A3yi4" # Your ProjectV2 Node ID
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
        run: python .github/scripts/sync_backlog_sprints.py
